name: test9372828
version: "master"
summary: dino (XMPP Client)
description: |
  Modern Jabber/XMPP Client using GTK+/Vala

base: core18
confinement: devmode

apps:
  dino-im:
    extensions: [gnome-3-28]
    command: bin/dino

parts:
  dino-im:
    plugin: autotools
    configflags: --disable-plugin=openpgp
    source-type: git
    source: https://github.com/dino/dino.git
    build-packages:
      - cmake
      - valac
      - libgee-0.8-dev
      - libsqlite3-dev
      - libgtk-3-dev
      - libnotify-dev
      - libgpgme-dev
      - libsoup2.4-dev
      - libgcrypt20-dev
      - libqrencode-dev
      - gettext
    stage-packages:
      - libassuan0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgee-0.8-2
      - libgpgme11
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libicu60
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libqrencode3
      - libsoup2.4-1
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
